# Generated by Django 5.2.4 on 2025-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerquoterequest'),
        ('fpo', '0003_fpoquoterequest_fpobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerquoterequest',
            name='accepted_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_quote', to='fpo.fpobid'),
        ),
        migrations.AddField(
            model_name='farmerquoterequest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='farmer.farmer'),
        ),
    ]
