# Generated by Django 5.2.4 on 2025-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpo', '0003_fpoquoterequest_fpobid'),
        ('retailer', '0002_retailer_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(help_text='In days')),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('air', 'Air')], default='road', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('small_truck', 'Small Truck'), ('medium_truck', 'Medium Truck'), ('large_truck', 'Large Truck'), ('articulated_truck', 'Articulated Truck')], max_length=20, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='fpo.fpoquoterequest')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='retailer.retailer')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
    ]
