# Generated by Django 5.2.4 on 2025-09-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerquoterequest'),
        ('fpo', '0002_fpo_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPOQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awarded', 'Awarded'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deadline'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FPOBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(help_text='In days')),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('air', 'Air')], default='road', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('small_truck', 'Small Truck'), ('medium_truck', 'Medium Truck'), ('large_truck', 'Large Truck'), ('articulated_truck', 'Articulated Truck')], max_length=20, null=True)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='fpo.fpo')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='farmer.farmerquoterequest')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
    ]
